module  . exports=[
                {
                 "storyno":1,
                 "storyname":"Reward For the gate keeper. ",
                 "parts":5,
                 "continueadd":" ",
                 "1":"Listen on great king Vikram,  Once upon a time there lived a king named Chandrakant   .  He was very popular due to his valour and generous nature  .  One day, a guard, who was responsible for guarding the main entrance of the palace, came to him and told him, His Majesty! You must alert our soldiers, as the enemy’s army might attack our country within a few days  .  Chandrakant asked him how he could say that beforehand  .  The guard did not give a proper reply to that and said that it was just a hunch   . ",
                 "2":" After a few days, the neighbouring country did launch a massive attack on Chandrakant’s kingdom, but as his soldiers were alert, they were able to counter the attack  .  The enemies were vanquished and king Chandrakant was able to save his kingdom  . ",
                 "3":"Once the war was over, he decided to give a suitable reward to the guard for his accurate information   .  ",
                 "4":"Next day, the guard was summoned in the court to receive his reward from the king   .  The king asked him once again that how he could predict so accurately that the enemies were going to attack the kingdom  .  The guard replied, “Sir I can see things which are going to happen in my dreams  .  One night, while I was doing my duty, I had a dream about the enemy army attacking us  . ” After hearing this, the king gave him one thousand gold coins  .  And then, suddenly he said to the   guard in a firm tone, “You are dismissed from the post of the guard,” Everyone in the king’s court was surprised by the king’s decision, but no one dared to ask him why  .  The guard quietly accepted the king’s decision  .  He bowed down before the king and went away  . ",
                 "5":" Vikram, say yes if you think that what king did was  right or else say no if you disagree with chandrakant's decision .",
                 "answer":"yes",
                 "repeatques":"say yes if you think that what king did was  right or else say no if you disagree with chandrakant's decision .",
                 "answeradd":" ",
                 "explain":" the duty of a guard is to take care of the palace’s gate . As the guard said, he had a dream during duty, the king got the idea that he was sleeping on duty . So, although he helped him win against the enemy army , he forgot to do his duty . That is why the king dismissed him from the post of the guard .So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit .<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>"
               },
               {
                "storyno":2,
                "storyname":"",
                "parts":7,
                "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great  king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> ",
                "1":"Listen on great king Vikram, Once upon a time, there lived a rich Brahmin by the name of Vishnuswamin, who was performing a huge sacrificial rite. He had three sons and each was extremely particular about three specific things. The eldest was fastidious about food, the second about women and the third about beds. ",
                "2":" Vishsnuswamin wanted a tortoise for his sacrifice. So, he sent his three sons to get one. They did find one, but each of them refused to touch it and bring it back home, as each claimed to be as fastidious as the other. ",
                "3":" A fierce quarrel broke out amongst them and they approached the king and requested him to decide who among them was the most fastidious. The king decided to test them all. He invited the first one to a very special feast prepared very exquisitely. But the first son, refused to touch the food claiming that the he smelt burnt corpses in the rice. On investigation, the king found that the rice was procured from a field near a cremation ground. The king was truly impressed. ",
                "4":" He then decided to test the second son by sending an extremely beautiful woman to him. But the second son sent her away saying that she smelt like a goat. On investigation, the king found that she had been fed goat milk in her childhood. The king was impressed by the second’s son’s fine taste in women. ",
                "5":" Then he decided to test the third son, by letting him sleep in a bed with seven huge mattresses. In the middle of the night, the third son awoke with a lot of pain and a red bruise on his shoulder. It was found that there was a strand of hair in the bed below the seven mattresses. ",
                "6":" The king was extremely impressed by the sensitivity of the third son as well. He could not decide who amongst the three was best, but employed them in his court and decided to use the special skills of the young men in his own interest. ",
                "7":" so vikram, Who among the three was the most fastidious? say first son  if you feel it was he ? ",
                "answer":"thirdson",
                "repeatques":"Who among the three was the most fastidious? say first son  if you feel it was he ? ",
                "answeradd":"The third son! was the most fastious ",
                "explain":"The bruise on his shoulder was a definite evidence of his sensitivity, while the other two sons could have obtained information from elsewhere too.<break time='0.25s'/> So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit ."
              },
              {
               "storyno":3,
               "storyname":"The exchanged heads",
               "parts":4,
               "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> ",
               "1":"Listen on great king Vikram, Once upon a time there lived a washerman named Dhavala. He once spotted a very beautiful lady at pond, who happened to be the daughter of another washerman. He instantly fell in love with her and pleaded with his parents to ask her parents for her hand in marriage. His parents did accordingly and the girl, Madanasundari, got married to him with her parents consent. She then went with Dhavala to live with him. ",
               "2":"Once the brother of Madanasundari, came to Dhavala to invite his sister and brother-in-law to their place for festival season. Dhavala agreed and the three of them were returning to Madanasundari's home. On the way they happened to pass by the temple of Durga Devi, the all powerful goddess of power. Her brother wanted to pay a visit to the goddess, and went to the temple. But as soon as he came near the goddess, he wanted to make a massive sacrifice to the goddess. So       saying  he cut his head off for the goddess. Madanasundari was worried and she then sent her husband to see what the matter was. On seeing the state of his brother-in-law, the husband was also moved deeply and he decided to offer his own head too to the goddess and cut his own head with his 10 scitmar. ",
               "3":" Madanasundari, after a long wait came and saw both her brother and husband lying on the ground and then decided to take her own life but asked the goddesss to get the same brother and husband in the next life. The goddess was pleased and stopped her from dying and asked her to join their heads and bodies and then she granted them life. In a hurry, Madanasundari, exchanged the heads of her brother and husband and was perplexed. ",
               "4":"so vikram, Who among the two is the husband of Madanasundari? option a ,The body that carries her husband's head . option b , the body that carries her brother's head   .",
               "answer":"a",
               "repeatques":"Who among the two is the husband of Madanasundari? option a ,The body that carries her husband's head . option b , the body that carries her brother's head .",
               "answeradd":"The body that carries her husband's head is her husband.",
               "explain":" The head is the most important part of the human body, and the rest of the body is identified by the head.<break time='0.25s'/> So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit .",
             },
             {
              "storyno":4,
              "storyname":"The Strange Decision",
              "parts":6,
              "continueadd":'<audio src="https://s3.amazonaws.com/vikraam/catch.mp3"/>'+'great king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time="1s"/> .',
              "1":"Many years ago, in the village of Kishannagar there lived a strong and kind king- Rajendra. His queen Prema and the King were married for very long but they did not have a child. The King was very kind and just to his people. After many years the King and the queen were blessed with a baby girl. They named her Sona. ",
              "2":"Sona, being the only child, was loved immensely by her parents. She was given the freedom to choose what she wants. Not only was she sharp in studies, she was also proficient at bow and arrow and with the sword. Sona grew up fast and soon reached her marriageable age. Her parents wanted her to get married to a suitable suitor but Sona refused. She said, ‘Father, I will marry that man who is more skilled than me and shall defeat me in a bow arrow and sword competition.’",
              "3":"The King thought it was fair enough and so he made an announcement in his kingdom. Many suitors came thinking that it is a girl they have to fight. They will easily defeat a girl. But Sona proved each of them wrong. She easily defeated everyone and they had to go back home disappointed. ",
              "4":"Among the crowd was a young man named Uday. He came everyday to watch Sona fight. He observed her and soon learnt all the techniques and strategies that Sona used for her fights. He then presented himself to the King. When he fought Sona, and very cleverly and easily defeated her. The King then asked Uday from where he had learnt such skilled fighting technique. To this Uday told the king the truth that he had observed Sona and so learnt how to defeat her. ",
              "5":"Sona immediately replied, ‘You have defeated me, but I cannot marry you.’ To which Uday replied, ‘Yes, you should not marry me.’ The King and the queen were surprised at their decision. ",
              "6":"so vikram, say yes if you think that what uday did was  right or else say no if you disagree with uday's decision ",
              "answer":"yes",
              "repeatques":"say yes if you think that what uday did was  right or else say no if you disagree with uday's decision ",
              "answeradd":"yes, it was a rightful decision by Uday. ",
              "explain":" Uday had learnt all the strategies by observing Sona fight. This makes Sona a guru or Uday’s teacher. In Hindu culture, a teacher cannot marry a student. Sona realized that Uday was first her student and then a suitor. Uday also thought in the same manner and thus decided not to marry Sona. <break time='0.25s'/> So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit .",
            },
            {
             "storyno":5,
             "storyname":"The four boys who made a lion",
             "parts":4,
             "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great  king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> .",
             "1":" Once upon a time there lived four sons of a poor brahmin who taught them all the Vedas and the holy scriptures. On their parents death, they decided to go and stay with their mother's father. But on reaching there they found that they were unwelcome there and that their cousins were unreceptive to the brothers. Then the brothers decided to each go out into the world and learn a special skill and come back and meet at a common place after a while. ",
             "2":' So they dispersed and came back to the same place at the appointed time. Each told what he had learnt. The first one said, " I can create flesh of a creature from a single one of the creature". The second one said, " I know how to grow the hair and skin of a creature if it has flesh and bones." The third one said, "I can create the limbs of a creature if its form is complete with skin hair and flesh and bones". The fourth one said, " I know how to give life to that creature once it is complete in form with limbs". ',
             "3":"So they set off into the forest to find a piece of bone on which they could test their skills. The first one they found was a lion's. So each of them displayed his skill and created a live huge Lion, which as fate would have it, killed all four of them and sped away. ",
             "4":"so Vikram ,Who among the four brothers is responsible for the death of all of them? say first son if you think it was him . ",
             "answer":"fourthson",
             "repeatques":"Who among the four brothers is responsible for the death of all of them? say first son if you think it was him .",
             "answeradd":"The fourth one. ",
             "explain":" as he was the one who gave life to the  dead structure of bones flesh and limbs and hair.<break time='0.25s'/>   So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit ." ,
           },
           {
            "storyno":6,
            "storyname":"The three sensitive queens",
            "parts":5,
            "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great  king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> ",
            "1":"Once upon a time there lived a king of Ujjayani by name of Dharmadhvaja, who had three exquisitely sensitive queens. He loved all three of them very much, all of them were of unparalleled beauty. ",
            "2":"On one occasion, while the king was playing with the first queen, he ruffled her hair. The lotus flower on her ear fell over her thigh, and made a wound and she cried out loud. The king was surprised at her sensitivity and immediately requested medical attention for her. ",
            "3":" On another occasion, when he was with the second queen on a full moon night on the roof of his palace, the queen suddenly felt her skin burning of the moonlight. The king ordered medical attention for her too and was again surprised at her sensitivity. ",
            "4":"On third occasion, when he was with the third queen, she collpased on the floor on hearing of the sound of a mortar grinding rice, far far away. The king immediately ordered medical attention for her and was surprised too. Since then he took utmost care of his three ultra sensitive queens. ",
            "5":"so vikram,  Who among the three queens is the most sensitive?, say first one if you think it was she. ",
            "answer":"thirdone",
            "repeatques":"so vikram,  Who among the three queens is the most sensitive?, say first one if you think it was she. ",
            "answeradd":" The third queen, ",
            "explain":"because  those who are sensitive to the suffering of others are sensitive in the real sense of the word  . <break time='0.25s'/>  So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit ." ,

          },
          {
           "storyno":7,
           "storyname":"The true obligation is without self motive",
           "parts":4,
           "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great  king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> ",
            "1":"A king, named Jeemootvaahan, lived in Himaachal Pradesh. He was very religious, but his son Agnivaahan was very cruel. Agnivaahan expressed his esire of becoming king while his father was alive. He threatened him to forcefully descend him frm the throne if his desire was not fulfilled. Jeemootvaahan handed over his kingdom to his son Agnivaahan and went away to forest. ",
            "2":"Agnivaahan started many atrocities with his people. Jeemootvaahan was passing his life doing Tapasyaa. One day when he was singing Bhajan, he heard a cry of an old woman. He went to that woman and asked the reason of her crying. She said - I have only one son. Here lives a Daanav, he will eat my son tonight. Jeemootvaahan consoled her and said - Don't be so sad, mother. I will be very happy if my this body comes in use for somebody. I will become your son and will become the food of that Daanav. The old woman could not agree at this, but the king was firm on his decision, so she had to agree at last. ",
            "3":"In the evening the woman's son came back. She told him everything. Her son also didn't agree for this, and he asked king to go back, but the king flatly refused to go back, and somehow he made him agreed. Thus Jeemootvaahan became the food of the Daanav and the woman's son was saved. ",
            "4":" so vikram , do you think that, what king did was right? say yes if you think so or else say no . ",
           "answer":"no",
           "repeatques":"do you think that,  what king did was right? say yes if you think so or else say no ",
           "answeradd":"no , There is no obligation in this,  ",
           "explain":"  Jeemootvaahan sacrificed himself with the desire of Moksh and Punya. Who could not do anything for his own son, if he does something for the other's son, this is not logical. Jeemootvaahan should have given up his life instead of making his son king. He handed over his kingdom to a cruel person to rule and left his people to suffer under him, he cannot be pardoned for this.  <break time='0.25s'/> So King Vikram, since you opened your mouth and started speaking. the betal detached itself from you and went up the tree to hand upside down.<audio src='https://s3.amazonaws.com/vikraam/fly1.mp3'/> say catch betaal to catch him again and take him to the sage who is waiting for him or else say stop to exit ." ,

         },
         {
          "storyno":8,
          "storyname":"The true obligation is without self motive",
          "parts":8,
          "continueadd":"<audio src='https://s3.amazonaws.com/vikraam/catch.mp3'/>great  king vikram , You have successfully mounted Betaal on your shoulders and started walking towards the cremation ground, Again the  spirit of Betaal  is  narrating  a story to you. <break time='1s'/> ",
           "1":"The king of Malaya Desh Samarjeet was very brave and learned. There lived a rich man, named Chandramani. One day a courtier asked king's permission to say something to the king. The king permitted him. He said - 'Mahaaraaj, We have a rich man, named Chandramani in our kingdom. His daughter Manimaalaa is very beautiful. There is nobody else as beautiful as her. She is now of marriageable age, if you like her, you may marry her. ' ",
           "2":"Hearing this the king Samarjeet told that if she would be really beautiful, he will surely marry her. The courtier went away. After the courtier had left, the king called his trusted maid and said to her - 'you are my most trusted maid, find out something for me.'. 'command me please.' King said - Our Chandramani's daughter is very beautiful. Find out if she is worthy of becoming my wife. She replied - ' have also heard it, but I have never seen her. Saying this the maid went away. ",
           "3":"Vikram, When the maid saw Manimaalaa, she just got stunned to see her beauty. She was much more beautiful than what she heard. All wives of Samarjeet were nothing in comparison to her beauty. She came back from there and decided that she will observe her duty. If she will tell him the truth, then he will make her his wife and will be lost in her beauty and will lose his control on his kingdom. He will not be able to leave her even for a moment. ",
           "4":"So she told Samarjeet that his many wives were more beautiful than Manimaalaa. So the king changed his mind. In the meantime, Chandramani also came to know about this that the king had sent his trusted maid to see Manimaalaa. He immediately went to the king and was happily ready to give his daughter to the king. But the king refused his proposal and he came back disappointed. He then married her to the king's courtier Krishnaanand. They started living happily. ",
           "5":"After some time the king went to see his kingdom. As he was passing by the palace of Krishnaanand, he saw a woman standing at the window of its second floor. The king just stood seeing her. He could not believe his eyes that she could be a human being. She seemed to him an Apsaraa. He got restless and came back to his palace. He asked his soldiers to find out about the identity of that woman. They told him that she was the wife of Krishnaanand. ",
           "6":'When Krishnaanand came to know that the king has made an inquiry about his wife, he straightway came to the king. Samarjeet asked him - "Is she your wife?" "Yes, Sir." Krishnaanand further said - "She is the daughter of Chandramani." The king got shocked, "What?" He said - "Yes Sir, When you refused to marry her, I married her." The king dismissed him and called his maid whom he sent to find out about Manimaalaa. He asked her - "Why did you lie to me?" The maid said politely  "If I had told you the truth, you would lose your kingdom. I put my duty in front of my faithfulness, Sir. " ',
           "7":"The king got very angry at this. He ordered to kill her. Krishnaanand was hearing all this, he said - I am ready to give Manimaalaa to you, but please,  don't kill this maid. The king said - I don't touch other people's wives. When the maid requested him for some leniency, he expelled her instead of killing her. ",
           "8":"So vikram, Was the maid really at fault? say yes if you think so or else say no. ",
          "answer":"no",
          "repeatques":" Was the maid really at fault? say yes if you think so or else say no. ",
          "answeradd":"    ",
          "explain":"  The maid was certainly at fault by not being faithful to her master,  but this crime was committed at the cost of duty. That is why, in fact, Samarjeet had committed crime by expelling her, not that she was at fault .<break time='1s'/> Hey king vikram who have successfully reached the cremation. the sage is really very happy with you. You did a great job , congratulation . So bye for now. hope to see you soon. <audio src='https://s3.amazonaws.com/vikraam/title2.mp3'/>" ,

     },

         ]
